/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_animal_free(a: number): void;
export function __wbg_get_animal_x(a: number): number;
export function __wbg_set_animal_x(a: number, b: number): void;
export function __wbg_get_animal_y(a: number): number;
export function __wbg_set_animal_y(a: number, b: number): void;
export function __wbg_get_animal_rotation(a: number): number;
export function __wbg_set_animal_rotation(a: number, b: number): void;
export function __wbg_get_animal_vision(a: number, b: number): void;
export function __wbg_set_animal_vision(a: number, b: number, c: number): void;
export function __wbg_simulation_free(a: number): void;
export function simulation_new(a: number): number;
export function simulation_default_config(): number;
export function simulation_config(a: number): number;
export function simulation_world(a: number): number;
export function simulation_step(a: number, b: number): void;
export function simulation_train(a: number, b: number): void;
export function __wbg_world_free(a: number): void;
export function __wbg_get_world_animals(a: number, b: number): void;
export function __wbg_set_world_animals(a: number, b: number, c: number): void;
export function __wbg_get_world_foods(a: number, b: number): void;
export function __wbg_set_world_foods(a: number, b: number, c: number): void;
export function __wbg_food_free(a: number): void;
export function __wbg_get_food_x(a: number): number;
export function __wbg_set_food_x(a: number, b: number): void;
export function __wbg_get_food_y(a: number): number;
export function __wbg_set_food_y(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
